CREATE TABLE "CaseRecord" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT,"priority" TEXT NOT NULL DEFAULT 'medium',"status" TEXT NOT NULL DEFAULT 'open',"ownerId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "CaseRecord_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SecurityAlert" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT NOT NULL,"severity" TEXT NOT NULL,"confidence" INTEGER NOT NULL DEFAULT 50,"riskScore" INTEGER NOT NULL,"status" TEXT NOT NULL DEFAULT 'new',"source" TEXT NOT NULL,"ruleId" TEXT,"eventId" TEXT,"matchId" TEXT,"entities" JSONB,"mitre" TEXT[],"assigneeId" TEXT,"caseId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "SecurityAlert_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TimelineEntry" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"caseId" TEXT,"alertId" TEXT,"type" TEXT NOT NULL,"title" TEXT NOT NULL,"content" TEXT,"actorId" TEXT,"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "TimelineEntry_pkey" PRIMARY KEY ("id"));
CREATE TABLE "EntityRisk" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"entityType" TEXT NOT NULL,"entityKey" TEXT NOT NULL,"score" INTEGER NOT NULL,"reasons" JSONB NOT NULL,"updatedAt" TIMESTAMP(3) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "EntityRisk_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Playbook" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT,"version" INTEGER NOT NULL DEFAULT 1,"status" TEXT NOT NULL DEFAULT 'draft',"actions" JSONB NOT NULL,"createdBy" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Playbook_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PlaybookExecution" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"playbookId" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'pending_approval',"requestedBy" TEXT NOT NULL,"approvedBy" TEXT,"input" JSONB,"result" JSONB,"idempotencyKey" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "PlaybookExecution_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ThreatIndicator" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"type" TEXT NOT NULL,"value" TEXT NOT NULL,"confidence" INTEGER NOT NULL,"severity" TEXT NOT NULL,"source" TEXT NOT NULL,"validUntil" TIMESTAMP(3),"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ThreatIndicator_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "SecurityAlert_matchId_key" ON "SecurityAlert"("matchId");
CREATE INDEX "SecurityAlert_tenantId_status_createdAt_idx" ON "SecurityAlert"("tenantId","status","createdAt");
CREATE INDEX "SecurityAlert_tenantId_severity_idx" ON "SecurityAlert"("tenantId","severity");
CREATE INDEX "SecurityAlert_tenantId_riskScore_idx" ON "SecurityAlert"("tenantId","riskScore");
CREATE INDEX "CaseRecord_tenantId_status_updatedAt_idx" ON "CaseRecord"("tenantId","status","updatedAt");
CREATE INDEX "TimelineEntry_tenantId_createdAt_idx" ON "TimelineEntry"("tenantId","createdAt");
CREATE INDEX "TimelineEntry_caseId_createdAt_idx" ON "TimelineEntry"("caseId","createdAt");
CREATE UNIQUE INDEX "EntityRisk_tenantId_entityType_entityKey_key" ON "EntityRisk"("tenantId","entityType","entityKey");
CREATE INDEX "EntityRisk_tenantId_score_idx" ON "EntityRisk"("tenantId","score");
CREATE UNIQUE INDEX "Playbook_tenantId_name_version_key" ON "Playbook"("tenantId","name","version");
CREATE INDEX "Playbook_tenantId_status_idx" ON "Playbook"("tenantId","status");
CREATE UNIQUE INDEX "PlaybookExecution_tenantId_idempotencyKey_key" ON "PlaybookExecution"("tenantId","idempotencyKey");
CREATE INDEX "PlaybookExecution_tenantId_status_createdAt_idx" ON "PlaybookExecution"("tenantId","status","createdAt");
CREATE UNIQUE INDEX "ThreatIndicator_tenantId_type_value_source_key" ON "ThreatIndicator"("tenantId","type","value","source");
CREATE INDEX "ThreatIndicator_tenantId_type_value_idx" ON "ThreatIndicator"("tenantId","type","value");
ALTER TABLE "SecurityAlert" ADD CONSTRAINT "SecurityAlert_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SecurityAlert" ADD CONSTRAINT "SecurityAlert_matchId_fkey" FOREIGN KEY ("matchId") REFERENCES "DetectionMatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SecurityAlert" ADD CONSTRAINT "SecurityAlert_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "CaseRecord"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "CaseRecord" ADD CONSTRAINT "CaseRecord_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TimelineEntry" ADD CONSTRAINT "TimelineEntry_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "CaseRecord"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TimelineEntry" ADD CONSTRAINT "TimelineEntry_alertId_fkey" FOREIGN KEY ("alertId") REFERENCES "SecurityAlert"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "EntityRisk" ADD CONSTRAINT "EntityRisk_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Playbook" ADD CONSTRAINT "Playbook_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PlaybookExecution" ADD CONSTRAINT "PlaybookExecution_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PlaybookExecution" ADD CONSTRAINT "PlaybookExecution_playbookId_fkey" FOREIGN KEY ("playbookId") REFERENCES "Playbook"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ThreatIndicator" ADD CONSTRAINT "ThreatIndicator_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
