ALTER TABLE "SecurityAlert" ADD COLUMN "incidentId" TEXT;
CREATE TABLE "CorrelationRule" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'draft',"windowMinutes" INTEGER NOT NULL,"threshold" INTEGER NOT NULL,"groupBy" TEXT NOT NULL,"severities" TEXT[],"outputSeverity" TEXT NOT NULL,"mitreTechniques" TEXT[],"createdBy" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "CorrelationRule_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SocIncident" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT NOT NULL,"severity" TEXT NOT NULL,"priority" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'new',"riskScore" INTEGER NOT NULL,"ownerId" TEXT,"deduplicationKey" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "SocIncident_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CorrelationSignal" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"ruleId" TEXT NOT NULL,"entityKey" TEXT NOT NULL,"alertIds" TEXT[],"score" INTEGER NOT NULL,"incidentId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "CorrelationSignal_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FeatureFlag" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"key" TEXT NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT false,"config" JSONB,"updatedBy" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "FeatureFlag_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RetentionPolicy" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"resource" TEXT NOT NULL,"retentionDays" INTEGER NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT true,"updatedBy" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "RetentionPolicy_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "CorrelationRule_tenantId_name_key" ON "CorrelationRule"("tenantId","name");
CREATE INDEX "CorrelationRule_tenantId_status_idx" ON "CorrelationRule"("tenantId","status");
CREATE UNIQUE INDEX "SocIncident_tenantId_deduplicationKey_key" ON "SocIncident"("tenantId","deduplicationKey");
CREATE INDEX "SocIncident_tenantId_status_updatedAt_idx" ON "SocIncident"("tenantId","status","updatedAt");
CREATE INDEX "SocIncident_tenantId_riskScore_idx" ON "SocIncident"("tenantId","riskScore");
CREATE INDEX "CorrelationSignal_tenantId_createdAt_idx" ON "CorrelationSignal"("tenantId","createdAt");
CREATE INDEX "CorrelationSignal_ruleId_entityKey_createdAt_idx" ON "CorrelationSignal"("ruleId","entityKey","createdAt");
CREATE UNIQUE INDEX "FeatureFlag_tenantId_key_key" ON "FeatureFlag"("tenantId","key");
CREATE UNIQUE INDEX "RetentionPolicy_tenantId_resource_key" ON "RetentionPolicy"("tenantId","resource");
CREATE INDEX "SecurityAlert_incidentId_idx" ON "SecurityAlert"("incidentId");
ALTER TABLE "CorrelationRule" ADD CONSTRAINT "CorrelationRule_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SocIncident" ADD CONSTRAINT "SocIncident_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CorrelationSignal" ADD CONSTRAINT "CorrelationSignal_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CorrelationSignal" ADD CONSTRAINT "CorrelationSignal_ruleId_fkey" FOREIGN KEY ("ruleId") REFERENCES "CorrelationRule"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CorrelationSignal" ADD CONSTRAINT "CorrelationSignal_incidentId_fkey" FOREIGN KEY ("incidentId") REFERENCES "SocIncident"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SecurityAlert" ADD CONSTRAINT "SecurityAlert_incidentId_fkey" FOREIGN KEY ("incidentId") REFERENCES "SocIncident"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "FeatureFlag" ADD CONSTRAINT "FeatureFlag_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RetentionPolicy" ADD CONSTRAINT "RetentionPolicy_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
